spring:
  datasource:
    username: c##wei
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate

  profiles:
    active: dev
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true

  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: cn.laike.management.blog.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty
      id-type: input
